export { default as Footer } from "./Footer"
export { default as Header } from "./Header"
export { default as GlobalStyles } from "./GlobalStyles"
export { default as PageTitleContent } from "./PageTitleContent"
export { default as SearchMovies } from "./SearchMovies"